# Generated by Django 3.0.3 on 2020-05-14 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('address', models.TextField(max_length=1000)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('mobile_number', models.CharField(max_length=100)),
                ('facebook_username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('date_graduated', models.DateField(blank=True, null=True)),
                ('honors', models.TextField(blank=True, max_length=1000)),
                ('officer_position', models.CharField(blank=True, max_length=100)),
                ('scholarships', models.TextField(blank=True, max_length=1000)),
                ('first_name_contact_person', models.CharField(max_length=100)),
                ('last_name_contact_person', models.CharField(max_length=100)),
                ('middle_name_contact_person', models.CharField(blank=True, max_length=100)),
                ('address_contact_person', models.CharField(max_length=1000)),
                ('mobile_number_contact_person', models.CharField(max_length=1000)),
                ('id_picture', models.ImageField(blank=True, upload_to='id_pictures')),
                ('payment_picture', models.ImageField(upload_to='payment_pictures')),
                ('enrolled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
