# Generated by Django 3.0.3 on 2020-05-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentstutorial_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttutorial',
            name='date_graduated',
        ),
        migrations.RemoveField(
            model_name='studenttutorial',
            name='honors',
        ),
        migrations.RemoveField(
            model_name='studenttutorial',
            name='officer_position',
        ),
    ]
