# Generated by Django 3.0.3 on 2020-05-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentstutorial_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttutorial',
            name='id_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studenttutorial',
            name='payment_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
