# Generated by Django 3.0.3 on 2020-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentstutorial_app', '0003_remove_studenttutorial_scholarships'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='studenttutorial',
            name='subjects_to_enroll',
            field=models.ManyToManyField(to='studentstutorial_app.Subjects'),
        ),
    ]
