# Generated by Django 3.0.3 on 2020-05-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app_1', '0004_auto_20200520_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled',
        ),
    ]
