# Generated by Django 3.0.3 on 2020-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app_1', '0005_remove_student_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_picture',
            field=models.ImageField(blank=True, upload_to='students_app_1/id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_picture',
            field=models.ImageField(upload_to='students_app_1/payment'),
        ),
    ]
