# Generated by Django 3.0.3 on 2020-05-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downloadable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('file', models.FileField(null=True, upload_to='')),
                ('is_ece', models.BooleanField()),
                ('is_ee', models.BooleanField()),
                ('is_tutorial', models.BooleanField()),
                ('is_accessible', models.BooleanField()),
            ],
        ),
    ]
