# Generated by Django 3.0.3 on 2020-05-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadables', '0002_auto_20200528_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadable',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='downloadables.DownloadableFile'),
        ),
    ]
