# Generated by Django 3.0.3 on 2020-06-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadables', '0004_auto_20200528_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadable',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
