# Generated by Django 3.0.3 on 2020-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloadables', '0005_handout_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadable',
            name='image',
            field=models.ImageField(null=True, upload_to='downloadables/thumbnails'),
        ),
        migrations.AlterField(
            model_name='downloadablefile',
            name='file',
            field=models.FileField(upload_to='downloadables/files'),
        ),
    ]
