# Generated by Django 3.0.3 on 2020-05-31 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('first_take', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveSmallIntegerField()),
                ('answer', models.CharField(max_length=5)),
                ('bonus', models.BooleanField(default=False)),
                ('skip', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('is_ece', models.BooleanField(default=False)),
                ('is_ee', models.BooleanField(default=False)),
                ('is_tutorial', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('answer_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams_app_2.AnswerKey')),
                ('answer_sheets', models.ManyToManyField(to='exams_app_2.AnswerSheet')),
            ],
        ),
        migrations.AddField(
            model_name='answersheet',
            name='items',
            field=models.ManyToManyField(to='exams_app_2.Item'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='items',
            field=models.ManyToManyField(to='exams_app_2.Item'),
        ),
    ]
