# Generated by Django 3.0.3 on 2020-05-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app_2', '0002_auto_20200531_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='examfile',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examfile',
            name='is_ece',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examfile',
            name='is_ee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examfile',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
