# Generated by Django 3.0.3 on 2020-05-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app_2', '0003_auto_20200531_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersheet',
            options={'ordering': ['score']},
        ),
    ]
