# Generated by Django 3.0.3 on 2020-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app_2', '0005_exam_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersheet',
            options={'ordering': ['-score']},
        ),
        migrations.AddField(
            model_name='exam',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
