# Generated by Django 3.0.3 on 2020-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app_2', '0006_auto_20200604_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='thumbnail',
            field=models.ImageField(upload_to='exams_app_2/thumbnails'),
        ),
        migrations.AlterField(
            model_name='examfile',
            name='file',
            field=models.FileField(upload_to='exams_app_2/examfiles'),
        ),
    ]
