# Generated by Django 3.0.3 on 2020-07-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app_2', '0008_auto_20200716_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='has_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='item_labels',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='percent_as',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='percent_bs',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='percent_corrects',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='percent_cs',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='percent_ds',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
