# Generated by Django 3.0.3 on 2020-07-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app_2', '0010_auto_20200716_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='thumbnail',
        ),
    ]
