# Generated by Django 3.0.3 on 2020-07-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app_2', '0011_auto_20200716_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-pk']},
        ),
    ]
