# Generated by Django 3.0.3 on 2020-05-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=1000)),
                ('question', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='mcq_images')),
                ('correct', models.CharField(max_length=1000)),
                ('wrong_1', models.CharField(max_length=1000)),
                ('wrong_2', models.CharField(blank=True, max_length=1000)),
                ('wrong_3', models.CharField(blank=True, max_length=1000)),
                ('correct_image', models.ImageField(blank=True, upload_to='mcq_images')),
                ('wrong_image_1', models.ImageField(blank=True, upload_to='mcq_images')),
                ('wrong_image_2', models.ImageField(blank=True, upload_to='mcq_images')),
                ('wrong_image_3', models.ImageField(blank=True, upload_to='mcq_images')),
                ('solution', models.CharField(blank=True, max_length=1000)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.Subtopic')),
            ],
        ),
    ]
