# Generated by Django 3.0.3 on 2020-05-13 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('address', models.TextField(max_length=1000)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('mobile_number', models.CharField(max_length=100)),
                ('facebook_username', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('date_graduated', models.DateField(blank=True)),
                ('honors', models.TextField(blank=True, max_length=1000)),
                ('officer_position', models.CharField(blank=True, max_length=100)),
                ('scholarships', models.TextField(blank=True, max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('first_name_contact_person', models.CharField(max_length=100)),
                ('last_name_contact_person', models.CharField(max_length=100)),
                ('middle_name_contact_person', models.CharField(blank=True, max_length=100)),
                ('address_contact_person', models.CharField(max_length=1000)),
                ('mobile_number_contact_person', models.CharField(max_length=1000)),
                ('id_picture', models.ImageField(blank=True, upload_to='id_pictures')),
                ('payment_picture', models.ImageField(upload_to='payment_pictures')),
                ('enrolled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Subsubtopic',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Subtopic')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='null', max_length=1000)),
                ('question', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='mcq_images')),
                ('correct', models.CharField(max_length=1000)),
                ('wrong_1', models.CharField(max_length=1000)),
                ('wrong_2', models.CharField(blank=True, max_length=1000)),
                ('wrong_3', models.CharField(blank=True, max_length=1000)),
                ('correct_image', models.ImageField(blank=True, upload_to='mcq_images')),
                ('wrong_image_1', models.ImageField(blank=True, upload_to='mcq_images')),
                ('wrong_image_2', models.ImageField(blank=True, upload_to='mcq_images')),
                ('wrong_image_3', models.ImageField(blank=True, upload_to='mcq_images')),
                ('solution', models.CharField(blank=True, max_length=1000)),
                ('subsubtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Subsubtopic')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicsStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(max_length=50)),
                ('conditional_subject', models.CharField(max_length=50)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(max_length=50)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Student')),
            ],
        ),
    ]
