# Generated by Django 3.0.3 on 2020-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_picture',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payment_picture',
        ),
        migrations.AddField(
            model_name='electricalstudent',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricalstudent',
            name='id_picture',
            field=models.ImageField(blank=True, upload_to='id_pictures'),
        ),
        migrations.AddField(
            model_name='electricalstudent',
            name='payment_picture',
            field=models.ImageField(default=12, upload_to='payment_pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronicsstudent',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electronicsstudent',
            name='id_picture',
            field=models.ImageField(blank=True, upload_to='id_pictures'),
        ),
        migrations.AddField(
            model_name='electronicsstudent',
            name='payment_picture',
            field=models.ImageField(default=12, upload_to='payment_pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialstudent',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorialstudent',
            name='id_picture',
            field=models.ImageField(blank=True, upload_to='id_pictures'),
        ),
        migrations.AddField(
            model_name='tutorialstudent',
            name='payment_picture',
            field=models.ImageField(default=12, upload_to='payment_pictures'),
            preserve_default=False,
        ),
    ]
