# Generated by Django 3.0.3 on 2020-05-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='author',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
