# Generated by Django 3.0.3 on 2020-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_ece',
            field=models.BooleanField(default=False, verbose_name='ece status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ee',
            field=models.BooleanField(default=False, verbose_name='ee status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tutorial',
            field=models.BooleanField(default=False, verbose_name='tutorial status'),
        ),
    ]
