# Generated by Django 3.0.3 on 2020-05-12 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20200505_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=1000)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('facebook_username', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('review_schedule', models.CharField(blank=True, max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('date_graduated', models.DateField()),
                ('honors', models.CharField(blank=True, max_length=1000)),
                ('officer_position', models.CharField(blank=True, max_length=100)),
                ('scholarships', models.CharField(blank=True, max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('review_status', models.CharField(max_length=50)),
                ('conditional_subject', models.CharField(blank=True, max_length=50)),
                ('first_name_contact_person', models.CharField(max_length=100)),
                ('last_name_contact_person', models.CharField(max_length=100)),
                ('middle_name_contact_person', models.CharField(max_length=100)),
                ('address_contact_person', models.CharField(max_length=1000)),
                ('mobile_number_contact_person', models.CharField(max_length=1000)),
                ('id_picture', models.ImageField(blank=True, upload_to='id_pictures')),
                ('payment_picture', models.ImageField(upload_to='payment_pictures')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
