# Generated by Django 3.0.3 on 2020-05-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200513_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalstudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Student'),
        ),
        migrations.AlterField(
            model_name='electronicsstudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Student'),
        ),
        migrations.AlterField(
            model_name='tutorialstudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Student'),
        ),
    ]
