# Generated by Django 3.0.3 on 2020-05-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200516_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exam_credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
