# Generated by Django 3.0.3 on 2020-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200512_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='undefined', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
