# Generated by Django 3.0.3 on 2020-06-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200604_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-timestamp']},
        ),
    ]
