# Generated by Django 3.0.3 on 2020-04-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0007_auto_20200422_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
