# Generated by Django 3.0.3 on 2020-06-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_accesscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessCount',
        ),
    ]
