# Generated by Django 3.0.3 on 2020-07-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_activity_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_ece',
            field=models.BooleanField(default=False, verbose_name='ece status'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_ee',
            field=models.BooleanField(default=False, verbose_name='ee status'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_tutorial',
            field=models.BooleanField(default=False, verbose_name='tutorial status'),
        ),
    ]
