# Generated by Django 3.0.3 on 2020-07-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200716_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-pk']},
        ),
    ]
