# Generated by Django 3.0.3 on 2020-05-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsee_app', '0002_auto_20200517_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentee',
            name='exam_tickets',
        ),
    ]
