# Generated by Django 3.0.3 on 2020-06-09 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('correct', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('is_ece', models.BooleanField(default=False)),
                ('is_ee', models.BooleanField(default=False)),
                ('is_tutorial', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MCQAccessCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('explanation', models.CharField(max_length=1000, null=True)),
                ('access_count', models.ManyToManyField(to='exams_app_3.MCQAccessCount')),
                ('choices', models.ManyToManyField(to='exams_app_3.Choice')),
            ],
            options={
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='ExamTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(null=True)),
                ('date_finish', models.DateTimeField(null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('items', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(null=True)),
                ('answers', models.ManyToManyField(to='exams_app_3.Choice')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_app_3.Exam')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='items',
            field=models.ManyToManyField(to='exams_app_3.MCQ'),
        ),
    ]
