# Generated by Django 3.0.3 on 2020-06-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('testimony', models.CharField(max_length=3000)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
