# Generated by Django 3.0.3 on 2020-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handouts', '0005_handout_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handout',
            name='image',
            field=models.ImageField(null=True, upload_to='handouts/thumbnails'),
        ),
        migrations.AlterField(
            model_name='handoutfile',
            name='file',
            field=models.FileField(upload_to='handouts/handoutfile'),
        ),
    ]
