# Generated by Django 3.0.3 on 2020-05-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsece_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentece',
            name='course',
        ),
    ]
