# Generated by Django 3.0.3 on 2020-05-17 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0006_examticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentsece_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentece',
            name='exam_tickets',
            field=models.ManyToManyField(to='exams_app.ExamTicket'),
        ),
        migrations.AlterField(
            model_name='studentece',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
