# Generated by Django 3.0.3 on 2020-05-15 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subsubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_app.Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=5000)),
                ('choice1', models.TextField(default='', max_length=1000)),
                ('choice2', models.TextField(default='', max_length=1000)),
                ('choice3', models.TextField(default='', max_length=1000)),
                ('choice4', models.TextField(default='', max_length=1000)),
                ('correct1', models.BooleanField(default=False)),
                ('correct2', models.BooleanField(default=False)),
                ('correct3', models.BooleanField(default=False)),
                ('correct4', models.BooleanField(default=False)),
                ('explanation', models.TextField(max_length=5000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_app.Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_app.Subcategory')),
                ('subsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_app.Subsubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_app.Exam')),
                ('exam_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='mcq1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq1', to='exams_app.MCQuestion'),
        ),
        migrations.AddField(
            model_name='exam',
            name='mcq2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq2', to='exams_app.MCQuestion'),
        ),
        migrations.AddField(
            model_name='exam',
            name='mcq3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq3', to='exams_app.MCQuestion'),
        ),
        migrations.AddField(
            model_name='exam',
            name='mcq4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq4', to='exams_app.MCQuestion'),
        ),
        migrations.AddField(
            model_name='exam',
            name='mcq5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq5', to='exams_app.MCQuestion'),
        ),
    ]
