# Generated by Django 3.0.3 on 2020-05-16 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('categoryas', models.ManyToManyField(to='exams_app.CategoryA')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('choice1', models.TextField(default='', max_length=500)),
                ('choice2', models.TextField(default='', max_length=500)),
                ('choice3', models.TextField(default='', max_length=500)),
                ('choice4', models.TextField(default='', max_length=500)),
                ('correct1', models.BooleanField(default=False)),
                ('correct2', models.BooleanField(default=False)),
                ('correct3', models.BooleanField(default=False)),
                ('correct4', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('explanation', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='examresults',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examresults',
            name='exam_taker',
        ),
        migrations.RemoveField(
            model_name='mcquestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mcquestion',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='mcquestion',
            name='subsubcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mcq1',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mcq2',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mcq3',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mcq4',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mcq5',
        ),
        migrations.AddField(
            model_name='exam',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_ece',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_ee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_premium',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ExamResults',
        ),
        migrations.DeleteModel(
            name='MCQuestion',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.DeleteModel(
            name='Subsubcategory',
        ),
        migrations.AddField(
            model_name='categorya',
            name='exams',
            field=models.ManyToManyField(to='exams_app.Exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='items',
            field=models.ManyToManyField(to='exams_app.MCQ'),
        ),
    ]
