# Generated by Django 3.0.3 on 2020-05-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0003_auto_20200517_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorya',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoryb',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
