# Generated by Django 3.0.3 on 2020-05-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0004_auto_20200517_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorya',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorya',
            name='is_ece',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorya',
            name='is_ee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorya',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorya',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryb',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryb',
            name='is_ece',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryb',
            name='is_ee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryb',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryb',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
