# Generated by Django 3.0.3 on 2020-05-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0005_auto_20200517_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(null=True)),
                ('score', models.PositiveSmallIntegerField(null=True)),
                ('percentage', models.FloatField(null=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams_app.Exam')),
            ],
        ),
    ]
