# Generated by Django 3.0.3 on 2020-05-17 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams_app', '0006_examticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='examticket',
            name='items',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categorya',
            name='exams',
            field=models.ManyToManyField(blank=True, to='exams_app.Exam'),
        ),
        migrations.AlterField(
            model_name='categoryb',
            name='categoryas',
            field=models.ManyToManyField(blank=True, to='exams_app.CategoryA'),
        ),
    ]
