# Generated by Django 3.0.3 on 2020-05-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0007_auto_20200517_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examticket',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams_app.Exam'),
        ),
    ]
