# Generated by Django 3.0.3 on 2020-05-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0008_auto_20200517_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorya',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='categoryb',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_premium',
        ),
    ]
