# Generated by Django 3.0.3 on 2020-05-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0009_auto_20200518_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examticket',
            name='items',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examticket',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
