# Generated by Django 3.0.3 on 2020-05-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0010_auto_20200519_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='choice1',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='choice2',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='choice3',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='choice4',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='correct1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='correct2',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='correct3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='correct4',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='explanation',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
