# Generated by Django 3.0.3 on 2020-05-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0011_auto_20200520_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('correct', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('explanation', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='correct1',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='correct2',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='correct3',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='correct4',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='image4',
        ),
        migrations.AddField(
            model_name='mcq',
            name='choices',
            field=models.ManyToManyField(to='exams_app.Choice'),
        ),
    ]
