# Generated by Django 3.0.3 on 2020-05-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0012_auto_20200522_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='explanation',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
