# Generated by Django 3.0.3 on 2020-06-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0015_auto_20200606_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['?']},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='author',
        ),
    ]
