# Generated by Django 3.0.3 on 2020-06-09 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams_app', '0016_auto_20200607_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcq',
            options={'ordering': ['?']},
        ),
        migrations.CreateModel(
            name='MCQAccessCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mcq',
            name='access_count',
            field=models.ManyToManyField(to='exams_app.MCQAccessCount'),
        ),
    ]
