# Generated by Django 3.0.3 on 2020-06-09 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams_app', '0017_auto_20200609_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqaccesscount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
