# Generated by Django 3.0.3 on 2020-06-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams_app', '0019_mcq_explanation_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mcq',
            options={},
        ),
    ]
